import { ImageData } from "../config";

export const FALLBACK_IMAGES: Omit<
  ImageData,
  "timestamp" | "expiresAt" | "blob"
>[] = [
  {
    id: "fallback_1",
    url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1920&q=80",
    source: "unsplash",
    downloadUrl: "https://unsplash.com/photos/mountain-landscape",
    author: "Damiano Baschiera",
    authorUrl: "https://unsplash.com/@damiano_baschiera",
  },
  {
    id: "fallback_2",
    url: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1920&q=80",
    source: "unsplash",
    downloadUrl: "https://unsplash.com/photos/nature-landscape",
    author: "David Marcu",
    authorUrl: "https://unsplash.com/@davidmarcu",
  },
  {
    id: "fallback_3",
    url: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1920&q=80",
    source: "unsplash",
    downloadUrl: "https://unsplash.com/photos/forest-path",
    author: "Casey Horner",
    authorUrl: "https://unsplash.com/@mischievous_penguins",
  },
  {
    id: "fallback_4",
    url: "https://images.unsplash.com/photo-1518837695005-2083093ee35b?w=1920&q=80",
    source: "unsplash",
    downloadUrl: "https://unsplash.com/photos/ocean-waves",
    author: "Sean Oulashin",
    authorUrl: "https://unsplash.com/@oulashin",
  },
  {
    id: "fallback_5",
    url: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=1920&q=80",
    source: "unsplash",
    downloadUrl: "https://unsplash.com/photos/northern-lights",
    author: "v2osk",
    authorUrl: "https://unsplash.com/@v2osk",
  },
  {
    id: "fallback_6",
    url: "https://images.unsplash.com/photo-1472214103451-9374bd1c798e?w=1920&q=80",
    source: "unsplash",
    downloadUrl: "https://unsplash.com/photos/mountain-sunset",
    author: "Luke Stackpoole",
    authorUrl: "https://unsplash.com/@withluke",
  },
  {
    id: "fallback_7",
    url: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=1920&q=80",
    source: "unsplash",
    downloadUrl: "https://unsplash.com/photos/lake-mountains",
    author: "Qingbao Meng",
    authorUrl: "https://unsplash.com/@ideasboom",
  },
  {
    id: "fallback_8",
    url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1920&q=80",
    source: "unsplash",
    downloadUrl: "https://unsplash.com/photos/tropical-beach",
    author: "Sean Oulashin",
    authorUrl: "https://unsplash.com/@oulashin",
  },
  {
    id: "fallback_9",
    url: "https://images.unsplash.com/photo-1511884642898-4c92249e20b6?w=1920&q=80",
    source: "unsplash",
    downloadUrl: "https://unsplash.com/photos/sand-dunes",
    author: "Sergey Pesterev",
    authorUrl: "https://unsplash.com/@sickle",
  },
  {
    id: "fallback_10",
    url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1920&q=80",
    source: "unsplash",
    downloadUrl: "https://unsplash.com/photos/starry-night",
    author: "Vincentiu Solomon",
    authorUrl: "https://unsplash.com/@vincentiu",
  },
  {
    id: "fallback_11",
    url: "https://images.unsplash.com/photo-1426604966848-d7adac402bff?w=1920&q=80",
    source: "unsplash",
    downloadUrl: "https://unsplash.com/photos/forest-green",
    author: "Casey Horner",
    authorUrl: "https://unsplash.com/@mischievous_penguins",
  },
  {
    id: "fallback_12",
    url: "https://images.unsplash.com/photo-1465146633011-14f8e0781093?w=1920&q=80",
    source: "unsplash",
    downloadUrl: "https://unsplash.com/photos/flower-field",
    author: "Tim Mossholder",
    authorUrl: "https://unsplash.com/@timmossholder",
  },
  {
    id: "fallback_13",
    url: "https://images.unsplash.com/photo-1475924156734-496f6cac6ec1?w=1920&q=80",
    source: "unsplash",
    downloadUrl: "https://unsplash.com/photos/cloudy-sky",
    author: "Но Но",
    authorUrl: "https://unsplash.com/@nonocraft",
  },
  {
    id: "fallback_14",
    url: "https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=1920&q=80",
    source: "unsplash",
    downloadUrl: "https://unsplash.com/photos/canyon-landscape",
    author: "Harli Marten",
    authorUrl: "https://unsplash.com/@harlimarten",
  },
  {
    id: "fallback_15",
    url: "https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?w=1920&q=80",
    source: "unsplash",
    downloadUrl: "https://unsplash.com/photos/mountain-lake",
    author: "Luca Bravo",
    authorUrl: "https://unsplash.com/@lucabravo",
  },
  {
    id: "fallback_16",
    url: "https://images.unsplash.com/photo-1497436072909-60f360e1d4b1?w=1920&q=80",
    source: "unsplash",
    downloadUrl: "https://unsplash.com/photos/coastline",
    author: "Bailey Zindel",
    authorUrl: "https://unsplash.com/@baileyzindel",
  },
  {
    id: "fallback_17",
    url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1920&q=80",
    source: "unsplash",
    downloadUrl: "https://unsplash.com/photos/alpine-meadow",
    author: "Damiano Baschiera",
    authorUrl: "https://unsplash.com/@damiano_baschiera",
  },
  {
    id: "fallback_18",
    url: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1920&q=80",
    source: "unsplash",
    downloadUrl: "https://unsplash.com/photos/galaxy",
    author: "Benjamin Voros",
    authorUrl: "https://unsplash.com/@vorosbenisop",
  },
  {
    id: "fallback_19",
    url: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=1920&q=80",
    source: "unsplash",
    downloadUrl: "https://unsplash.com/photos/rocky-coast",
    author: "Alex Perez",
    authorUrl: "https://unsplash.com/@alexperez",
  },
  {
    id: "fallback_20",
    url: "https://images.unsplash.com/photo-1495567720989-cebdbdd97913?w=1920&q=80",
    source: "unsplash",
    downloadUrl: "https://unsplash.com/photos/desert-landscape",
    author: "Sergey Pesterev",
    authorUrl: "https://unsplash.com/@sickle",
  },
];
